### PR TITLE
fix(aggiemap-angular): Update Sustainable Transporation map/layers with new source

### LINKED ISSUE #685: (aggiemap-angular): Sustainable transportation map & layer need updated sources for layers
### Issue 1:

After server federation sustainable transportation layers are not updating as changes are made. Layers will need to pull from the other Portal until we are able to migrate everything over and get a new editor set up for them with access for those who need it.

EV Charge Stations: https://arc.ts.tamu.edu/arcgis/rest/services/Hosted/EV_Charge_Stations/FeatureServer
Hub Corral, Shared Mobility Racks, Bike Racks: https://arc.ts.tamu.edu/arcgis/rest/services/Hosted/Rack_Locations/FeatureServer
Bike Fix Stations: https://arc.ts.tamu.edu/arcgis/rest/services/Hosted/Fix_Stations/FeatureServer
Bike Lanes: https://arc.ts.tamu.edu/arcgis/rest/services/Hosted/Bike_Lanes/FeatureServer
Dismount Zone: https://arc.ts.tamu.edu/arcgis/rest/services/Hosted/Dismount_Zones/FeatureServer

### Issue 2:
Removing Bike Rack Areas from the map. We will no longer include these on the map in an effort to simplify, as bike racks are already marked.

### PR DESCRIPTION
**Pull request by sloneearly**
This PR updates Sustainable Transportation (standalone map + layers on the main map) to this new URL for the data layers: https://gis.it.tamu.edu/arcgis/rest/services/TS/BikeMap/MapServer

## Standalone map:
Screenshot 2026-04-10 090405

## Main map with sustainable transporation layers on
image

## Popups working on both:

image

Closes #685

### CODE REVIEW

File: libs/aggiemap/ngx/common/src/lib/layer-sources/layer-sources.ts [hunk 1]
```diff
@@ -254,6 +254,7 @@ export function LayerSources(
           id: 'bike-dismount-zones-layer',
           title: 'Bike Dismount Zones',
           url: `${bikeMapUrl}/4`,
+<<<<<<< HEAD
```
Comment (sloneearly) [inline libs/aggiemap/ngx/common/src/lib/layer-sources/layer-sources.ts:257]: This might be the dumbest thing I've ever done LOL

**Review by danielgoldbergtamu — APPROVED** [review]
Thanks.
